name: Build SDK Package

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Source Code Scan
        uses: SonarSource/sonarcloud-github-action@master
        env: 
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=dvir-segal
            -Dsonar.projectKey=Dvir-Segal_harmony-endpoint-management-py-sdk
            -Dsonar.branch.name=release
      - uses: sonarsource/sonarqube-quality-gate-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN  }}
        with:
          args: >
            -Dsonar.qualitygate.exitonerror=true
          
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
      - name: Build SDK
        run: |
          python -m pip install -r ./requirements.txt
          export BRANCH_NAME=${GITHUB_REF#refs/heads/}
          export BUILD_JOB_ID=$GITHUB_RUN_ID
          export BUILD_VERSION=$(python setup.py --version)
          python ./sdk_generator/generate_sdk.py

      - name: Artifact Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=dvir-segal
            -Dsonar.projectKey=Dvir-Segal_artifact
            -Dsonar.branch.name=master
            -Dsonar.sources=chkp_harmony_endpoint_management_sdk
            -Dsonar.projectBasedir=chkp_harmony_endpoint_management_sdk

      - uses: sonarsource/sonarqube-quality-gate-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.qualitygate.exitonerror=true

      - uses: actions/upload-artifact@v4
        with:
          name: chkp_harmony_endpoint_management_sdk
          path: chkp_harmony_endpoint_management_sdk
    
